//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public short packid { get; set; }
        public Nullable<short> no_of_days { get; set; }
        public string designation { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
