//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public short bookid { get; set; }
        public Nullable<short> packid { get; set; }
        public Nullable<short> custid { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string couponcode { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> totalprice { get; set; }
    }
}
