//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        public int couponid { get; set; }
        public string couponcode { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<System.DateTime> tilldate { get; set; }
    }
}
